"""Expanded WAF / CDN fingerprint signatures.
Publicly documented header, cookie, server and block-page markers.
"""

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "cf-connecting-ip"],
        "cookies": ["__cfduid", "cf_clearance", "__cf_bm"],
        "server": ["cloudflare"],
        "block_page_markers": ["attention required", "cloudflare ray id", "cf-error-details", "sorry, you have been blocked"],
    },
    "Akamai": {
        "headers": ["akamai-ghost-ip", "x-akamai-transformed", "akamai-origin-hop"],
        "cookies": ["ak_bmsc", "bm_sv", "bm_mi"],
        "server": ["akamaighost", "akamai"],
        "block_page_markers": ["access denied", "reference #", "akamai"],
    },
    "Imperva / Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["incap_ses", "visid_incap", "nlbi_"],
        "server": [],
        "block_page_markers": ["incapsula incident id", "request unsuccessful", "incapsula"],
    },
    "AWS WAF / CloudFront": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amz-cf-pop", "x-cache"],
        "cookies": ["awsalb", "awsalbcors", "aws-waf-token"],
        "server": ["cloudfront"],
        "block_page_markers": ["the request could not be satisfied", "generated by cloudfront", "request blocked"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache", "x-sucuri-block"],
        "cookies": [],
        "server": ["sucuri/cloudproxy", "sucuri"],
        "block_page_markers": ["access denied - sucuri website firewall", "sucuri website firewall"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-wa-info", "x-cnection"],
        "cookies": ["ts", "bigipserver", "f5_"],
        "server": ["big-ip", "bigip"],
        "block_page_markers": ["the requested url was rejected", "support id", "request rejected"],
    },
    "ModSecurity": {
        "headers": [],
        "cookies": [],
        "server": ["mod_security", "modsecurity"],
        "block_page_markers": ["mod_security", "not acceptable", "modsecurity"],
    },
    "Barracuda": {
        "headers": [],
        "cookies": ["barra_counter_session", "barracuda_"],
        "server": [],
        "block_page_markers": ["barracuda", "barra"],
    },
    "Fortinet FortiWeb": {
        "headers": ["fortiwafsid"],
        "cookies": ["fortiwafsid"],
        "server": [],
        "block_page_markers": ["fortiweb", "fortigate"],
    },
    "Fastly": {
        "headers": ["x-served-by", "x-cache", "x-timer", "fastly-restarts"],
        "cookies": [],
        "server": ["fastly"],
        "block_page_markers": ["fastly error", "error from fastly"],
    },
    "Azure Front Door / Application Gateway": {
        "headers": ["x-azure-ref", "x-msedge-ref", "x-azure-socketip"],
        "cookies": [],
        "server": [],
        "block_page_markers": ["azure", "the request is blocked"],
    },
    "Wordfence": {
        "headers": [],
        "cookies": ["wfwaf-authcookie"],
        "server": [],
        "block_page_markers": ["generated by wordfence", "wordfence"],
    },
    "StackPath / Highwinds": {
        "headers": ["x-sp-url", "x-hw"],
        "cookies": [],
        "server": [],
        "block_page_markers": ["stackpath"],
    },
    "Citrix NetScaler / ADC": {
        "headers": ["ns_af", "citrix_ns_id"],
        "cookies": ["ns_af", "citrix_ns_id", "nsC"],
        "server": [],
        "block_page_markers": ["netscaler", "citrix"],
    },
    "DenyAll / Rapid7": {
        "headers": [],
        "cookies": [],
        "server": [],
        "block_page_markers": ["denyall", "rweb"],
    },
}
